hide:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: classdash
    id:
      required: true
      example: "a1b2c3"
      selector:
        text:

unhide:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: classdash
    id:
      required: true
      example: "a1b2c3"
      selector:
        text:

mute:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: classdash
    id:
      required: true
      example: "a1b2c3"
      selector:
        text:

unmute:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: classdash
    id:
      required: true
      example: "a1b2c3"
      selector:
        text:

create_virtual_reminder:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: classdash
    title:
      required: true
      example: "Bring signed permission slip"
      selector:
        text:
    class:
      required: false
      selector:
        device:
          filter:
            integration: classdash
            model: "Class"
    due:
      required: false
      selector:
        datetime:

edit_virtual_reminder:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: classdash
    id:
      required: true
      example: "v-1a2b3c4d"
      selector:
        text:
    title:
      required: true
      example: "Bring signed permission slip"
      selector:
        text:
    class:
      required: false
      selector:
        device:
          filter:
            integration: classdash
            model: "Class"
    due:
      required: false
      selector:
        datetime:
